### ISSUE TITLE
ファイル内のclassに対応していない？

### ISSUE THREAD

**Issue by SeeLog** [shiba6v/shape_commentator#1]
# NameError: name '<クラス名>' is not defined

## 再現方法

Pytorchを用いてモデルを定義する際にクラスを用いて行うと，そのクラスを読み込む際にエラーが発生する．

具体的には以下のようなコードに対して `python3.6 -m shape_commentator test.py`を実行すると
```python
import torch
from torch import nn

class TestNN(nn.Module):
    def __init__(self, hidden_size):
        super(TestNN, self).__init__()
        self.testnn = nn.Linear(hidden_size, hidden_size)

    def forward(self, input_tensor):
        output = self.testnn(input_tensor)

        return output

dummy_input = torch.tensor([0.]*10)

test = TestNN(10)

dummy_output = test(dummy_input)
```

以下のエラーが発生します．(ファイルパスは一部隠しています)

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/.local/lib/python3.6/site-packages/shape_commentator/__main__.py", line 2, in <module>
    sp.main()
  File "~/.local/lib/python3.6/site-packages/shape_commentator/shape_commentator.py", line 162, in main
    execute(source,globals(),locals())
  File "~/.local/lib/python3.6/site-packages/shape_commentator/shape_commentator.py", line 114, in execute
    exec(code, globals, locals)
  File "<string>", line 17, in <module>
  File "<string>", line 7, in __init__
NameError: name 'TestNN' is not defined
```

**Comment by shiba6v** [comment]
ありがとうございます．
IPythonでは動作するようですが，`python -m shape_commentator test.py`で実行した際に同様のエラーが出ることを確認しました．
修正します．

**Comment by shiba6v** [comment]
v_0.1.4としてリリースしました．
