### ISSUE TITLE
Windowsへの対応？

### ISSUE THREAD

**Issue by masan4444** [shiba6v/shape_commentator#35]
windowsのanacondaプロンプト上でpipインストールすると，文字コードエラーによってインストールが停止する．
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-jff332fq\shape-commentator\setup.py", line 43, in <module>
        long_description=open("README.md").read(),
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 5454: illegal multibyte sequence
```
windows対応のつもりがなかったり，既出の問題であればすみません

**Comment by shiba6v** [comment]
修正し，バージョン0.5.2をリリースしました．
こちらのWindows + Anaconda Promptでも確認しましたが，もし良ければチェックしていただけるとありがたいです．

**Comment by masan4444** [comment]
0.5.2でインストールに成功しました
素早い対応ありがとうございます！！

**Comment by shiba6v** [comment]
ご報告ありがとうございました！
